#version 460

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba16f) writeonly uniform image2D outImage;

layout (push_constant) uniform Push {
    vec4 data1;
    vec4 data2;
    vec4 data3;
    vec4 data4;
} pc;

void main() {
    ivec2 size = imageSize(outImage);
    ivec2 coord = ivec2 (gl_GlobalInvocationID.xy);
    if (coord.x >= size.x || coord.y >= size.y) {
        return;
    }
    imageStore (outImage, coord, pc.data1);
}